/*
 * Automatically generated by 'ng g ng-alain:plugin icon'
 * @see https://ng-alain.com/cli/plugin#icon
 *
 * 圖標導入策略：
 * - 本檔案包含專案中實際使用的圖標
 * - 定期執行 `yarn icon` 可自動更新此檔案
 * - 僅導入需要的圖標以優化 bundle 大小
 *
 * 優化建議：
 * 1. 定期審查並移除未使用的圖標
 * 2. 使用 ng-alain icon 插件自動管理
 * 3. 考慮使用動態載入減少初始 bundle
 */

// 導航相關圖標 (高頻使用)
import {
  DashboardOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  AppstoreOutline,
  RocketOutline,
  ProjectOutline // 新增：對應 anticon-project
} from '@ant-design/icons-angular/icons';

// 用戶與權限相關
import {
  UserOutline,
  TeamOutline,
  LogoutOutline,
  LockOutline,
  UsergroupAddOutline // 新增：對應 anticon-usergroup-add
} from '@ant-design/icons-angular/icons';

// 操作相關圖標
import {
  SettingOutline,
  ToolOutline,
  DownloadOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  ScanOutline,
  PrinterOutline,
  ShareAltOutline
} from '@ant-design/icons-angular/icons';

// 通訊與社交
import {
  MailOutline,
  MessageOutline,
  GlobalOutline,
  GithubOutline,
  WeiboCircleOutline,
  AlipayCircleOutline,
  TaobaoCircleOutline,
  DingdingOutline,
  TaobaoOutline
} from '@ant-design/icons-angular/icons';

// 數據與分析
import { PieChartOutline, DatabaseOutline, HddOutline, CloudOutline, ApiOutline, ForkOutline } from '@ant-design/icons-angular/icons';

// 裝置與硬體
import { LaptopOutline, UsbOutline, CustomerServiceOutline, SoundOutline } from '@ant-design/icons-angular/icons';

// 內容與文檔
import { BookOutline, BorderLeftOutline, BorderRightOutline } from '@ant-design/icons-angular/icons';

// 商務與金融
import { PayCircleOutline, ShoppingCartOutline, TrophyOutline, CopyrightOutline } from '@ant-design/icons-angular/icons';

// 互動與反饋
import {
  LikeOutline,
  DislikeOutline,
  StarOutline,
  FrownOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline
} from '@ant-design/icons-angular/icons';

// 編輯與操作
import {
  EditOutline,
  DeleteOutline,
  SaveOutline,
  CloseOutline,
  CheckCircleOutline,
  CheckSquareOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  EyeOutline,
  EyeInvisibleOutline,
  SwapOutline,
  ReloadOutline,
  ZoomInOutline,
  ZoomOutOutline
} from '@ant-design/icons-angular/icons';

// 文件與內容
import { FileTextOutline, PaperClipOutline, PictureOutline, UnorderedListOutline } from '@ant-design/icons-angular/icons';

// 時間與狀態
import { ClockCircleOutline, HistoryOutline, PlayCircleOutline, PauseCircleOutline } from '@ant-design/icons-angular/icons';

// 通知與警告
import { NotificationOutline, WarningOutline, ExclamationCircleOutline } from '@ant-design/icons-angular/icons';

// 建築與部署
import { ApartmentOutline, ClusterOutline, ContainerOutline, DeploymentUnitOutline } from '@ant-design/icons-angular/icons';

// 圖表與數據視覺化
import { BarChartOutline, LineChartOutline, RadarChartOutline, FundOutline } from '@ant-design/icons-angular/icons';

// 位置與導航
import { HomeOutline, InboxOutline, FlagOutline } from '@ant-design/icons-angular/icons';

// 財務與交易
import { DollarOutline, TransactionOutline } from '@ant-design/icons-angular/icons';

// 用戶管理擴展
import { UserAddOutline, UserDeleteOutline, CrownOutline } from '@ant-design/icons-angular/icons';

// 特效與動作
import { ThunderboltOutline } from '@ant-design/icons-angular/icons';

/**
 * 自動生成的圖標列表
 * 包含專案中實際使用的所有圖標
 *
 * 維護建議：
 * - 新增圖標：執行 `yarn icon` 自動掃描並更新
 * - 移除未使用圖標：定期審查並手動移除
 * - 圖標命名：遵循 Ant Design 命名規範
 */
export const ICONS_AUTO = [
  // 導航相關 (Navigation)
  DashboardOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  AppstoreOutline,
  RocketOutline,
  ProjectOutline, // 新增

  // 用戶與權限 (User & Auth)
  UserOutline,
  TeamOutline,
  LogoutOutline,
  LockOutline,
  UsergroupAddOutline, // 新增

  // 操作相關 (Actions)
  SettingOutline,
  ToolOutline,
  DownloadOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  ScanOutline,
  PrinterOutline,
  ShareAltOutline,

  // 通訊與社交 (Communication & Social)
  MailOutline,
  MessageOutline,
  GlobalOutline,
  GithubOutline,
  WeiboCircleOutline,
  AlipayCircleOutline,
  TaobaoCircleOutline,
  DingdingOutline,
  TaobaoOutline,

  // 數據與分析 (Data & Analytics)
  PieChartOutline,
  DatabaseOutline,
  HddOutline,
  CloudOutline,
  ApiOutline,
  ForkOutline,

  // 裝置與硬體 (Devices & Hardware)
  LaptopOutline,
  UsbOutline,
  CustomerServiceOutline,
  SoundOutline,

  // 內容與文檔 (Content & Documents)
  BookOutline,
  BorderLeftOutline,
  BorderRightOutline,

  // 商務與金融 (Business & Finance)
  PayCircleOutline,
  ShoppingCartOutline,
  TrophyOutline,
  CopyrightOutline,

  // 互動與反饋 (Interaction & Feedback)
  LikeOutline,
  DislikeOutline,
  StarOutline,
  FrownOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,

  // 編輯與操作 (Edit & Actions)
  EditOutline,
  DeleteOutline,
  SaveOutline,
  CloseOutline,
  CheckCircleOutline,
  CheckSquareOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  EyeOutline,
  EyeInvisibleOutline,
  SwapOutline,
  ReloadOutline,
  ZoomInOutline,
  ZoomOutOutline,

  // 文件與內容 (Files & Content)
  FileTextOutline,
  PaperClipOutline,
  PictureOutline,
  UnorderedListOutline,

  // 時間與狀態 (Time & Status)
  ClockCircleOutline,
  HistoryOutline,
  PlayCircleOutline,
  PauseCircleOutline,

  // 通知與警告 (Notifications & Warnings)
  NotificationOutline,
  WarningOutline,
  ExclamationCircleOutline,

  // 建築與部署 (Architecture & Deployment)
  ApartmentOutline,
  ClusterOutline,
  ContainerOutline,
  DeploymentUnitOutline,

  // 圖表與數據視覺化 (Charts & Data Visualization)
  BarChartOutline,
  LineChartOutline,
  RadarChartOutline,
  FundOutline,

  // 位置與導航 (Location & Navigation)
  HomeOutline,
  InboxOutline,
  FlagOutline,

  // 財務與交易 (Finance & Transactions)
  DollarOutline,
  TransactionOutline,

  // 用戶管理擴展 (User Management Extended)
  UserAddOutline,
  UserDeleteOutline,
  CrownOutline,

  // 特效與動作 (Effects & Actions)
  ThunderboltOutline
];
